"""empty message

Revision ID: cb47051b3d97
Revises: 80d167e8eab8
Create Date: 2020-09-05 17:57:14.201400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb47051b3d97'
down_revision = '80d167e8eab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currently_reading', sa.Column('page_number', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'currently_reading', ['book_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currently_reading', type_='unique')
    op.drop_column('currently_reading', 'page_number')
    # ### end Alembic commands ###
