"""empty message

Revision ID: e5648bbd8c6b
Revises: cb47051b3d97
Create Date: 2020-09-05 18:34:58.253839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5648bbd8c6b'
down_revision = 'cb47051b3d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currently_reading', sa.Column('date_modified', sa.DateTime()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currently_reading', 'date_modified')
    # ### end Alembic commands ###
